name: Smart Home Floorplan
description: Smart Home Floorplan add-on
version: 0.0.2
slug: smarthomefloorplan
init: false
hassio_api: true
homeassistant_api: true
webui: http://[HOST]:[PORT:8099]/
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
image: docker.io/loelabs/shf-ha-addon-{arch}
startup: application
ingress: true
panel_icon: mdi:floor-plan
panel_title: Smart Home Floorplan
panel_admin: false
backup: cold
map:
- config:ro
- share:rw
- media:rw
- ssl:ro
options:
  propertyId: ''
  accessToken: ''
  versionCheckIntervalSeconds: 3600
schema:
  propertyId: str
  accessToken: str
  versionCheckIntervalSeconds: int(10,)
