name: Smart Home Floorplan (dev)
description: Smart Home Floorplan add-on
<<<<<<< HEAD
version: 0.0.0-t5n4um
=======
version: 0.0.0-t5n35q
>>>>>>> ac74e2f27a30c351d473276756ce32b3f10c31d2
slug: smarthomefloorplan
init: false
hassio_api: true
homeassistant_api: true
webui: http://[HOST]:[PORT:8099]/
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
image: loelabs/shf-ha-addon-{arch}
startup: application
stage: stable
ingress: true
panel_icon: mdi:floor-plan
panel_title: Smart Home Floorplan
panel_admin: false
backup: cold
map:
- config:ro
- share:rw
- media:rw
- ssl:ro
options:
  propertyId: ''
  accessToken: ''
  versionCheckIntervalSeconds: 3600
schema:
  propertyId: str
  accessToken: str
  versionCheckIntervalSeconds: int(10,)
